#spring#
spring:
  application:
    name: spring-boot
    #jpa#
  jpa:
    show-sql: false
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/admin
  # redis#
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  #rabbitmq#
  rabbitmq:
    connection-timeout: 10000
    host: 127.0.0.1
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    password: guest
    username: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    #jackson#
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
    #数据源#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/thebestdatabaseintheworld?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  # thymeleaf#
  thymeleaf:
    cache: false
    #server#
  profiles:
    include: other
    active:
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
    context-path: /
# actuator 监控
#Actuator就是一款可以帮助你监控系统数据的框架,其可以监控很多很多的系统数据,它有对应用系统的自省和监控的集成功能，可以查看应用配置的详细信息#
management:
  endpoint:
    #允许应用程序正常关闭
    shutdown:
      enabled: true
  endpoints:
    web:
      #在spring boot 2.0以后,actuator默认只开启了info和health两个端点,要想使用其他的端点,需要在application.yml中打开
      exposure:
        include: "*"
#log4j2配置文件#
logging:
  config: classpath:log4j2.xml
---
spring:
  profiles: no2
server:
  port: 8082






