spring:
  datasource:
    # 数据源的其他配置 #
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    asyncInit: true
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #配置监控统计拦截的filters
    filters: stat