#spring#
spring:
  application:
    name: spring-boot
    #jap#
  jpa:
    show-sql: true
  # redis#
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  #rabbitmq#
  rabbitmq:
    connection-timeout: 10000
    host: 127.0.0.1
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    password: guest
    username: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    #jackson#
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
    #数据源#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/thebestdatabaseintheworld?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 数据源的其他配置 #
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    asyncInit: true
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #配置监控统计拦截的filters
    filters: stat
  # thymeleaf#
  thymeleaf:
    cache: false
    #server#
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
    context-path: /
# actuator #
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
#log4j2配置文件#
logging:
  config: classpath:log4j2.xml







